service: burger-king-dependencias

provider:
  name: aws
  runtime: python3.13
  region: us-east-1
  iam:
    role: arn:aws:iam::${env:AWS_ACCOUNT_ID}:role/LabRole

layers:
  pythonDependencies:
    path: python-dependencies
    name: ${sls:stage, 'dev'}-burger-king-python-dependencies
    description: Capa compartida con dependencias Python para todos los microservicios de Burger King
    compatibleRuntimes:
      - python3.13
      - python3.12
    retain: false

resources:
  Outputs:
    PythonDependenciesLayerExport:
      Value:
        Ref: PythonDependenciesLambdaLayer
      Export:
        Name: BurgerKingPythonDependenciesLayer
    
    PythonDependenciesLayerVersion:
      Value:
        Ref: PythonDependenciesLambdaLayer
      Export:
        Name: BurgerKing-Python-Layer-Version