service: burger-king-catalogo

provider:
  name: aws
  runtime: python3.13
  region: us-east-1
  memorySize: 256
  timeout: 20
  iam:
    role: arn:aws:iam::${env:AWS_ACCOUNT_ID}:role/LabRole
  environment:
    TABLA_PRODUCTOS: ${env:TABLA_PRODUCTOS}
    BUCKET_PRODUCTOS: ${env:S3_BUCKET_CATALOGO}
  httpApi:
    cors: true
    authorizers:
      MiAutorizadorBurger:
        type: request
        functionArn: arn:aws:lambda:${aws:region}:${aws:accountId}:function:burger-king-autenticacion-dev-ValidarTokenAcceso
        payloadVersion: '2.0'
        enableSimpleResponses: true

functions:
  CreateProduct:
    handler: handlers/product_create.lambda_handler
    layers:
      - !ImportValue BurgerKing-Python-Layer-Version
    events:
      - httpApi:
          method: POST
          path: /productos/create
          authorizer:
            name: MiAutorizadorBurger

  UpdateProduct: 
    handler: handlers/product_update.lambda_handler
    layers:
      - !ImportValue BurgerKing-Python-Layer-Version
    events:
      - httpApi:
          method: PUT
          path: /productos/update
          authorizer:
            name: MiAutorizadorBurger

  DeleteProduct:
    handler: handlers/product_delete.lambda_handler
    layers:
      - !ImportValue BurgerKing-Python-Layer-Version
    events:
      - httpApi:
          method: DELETE
          path: /productos/delete
          authorizer:
            name: MiAutorizadorBurger

  ProductID:
    handler: handlers/product_id.lambda_handler
    layers:
      - !ImportValue BurgerKing-Python-Layer-Version
    events:
      - httpApi:
          method: POST 
          path: /productos/id

  ListProduct:
    handler: handlers/product_list.lambda_handler
    layers:
      - !ImportValue BurgerKing-Python-Layer-Version
    events:
      - httpApi:
          method: POST
          path: /productos/list

resources:
  Resources:
    ProductosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:TABLA_PRODUCTOS}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: local_id
            AttributeType: S
          - AttributeName: producto_id
            AttributeType: S
        KeySchema:
          - AttributeName: local_id
            KeyType: HASH
          - AttributeName: producto_id
            KeyType: RANGE