org: ${env:ORG_NAME}
app: burger-king-backend
stage: dev

services:
  dependencias:
    path: dependencias

  api-autenticacion:
    path: autenticacion
    dependsOn:
      - dependencias

  api-catalogo:
    path: catalogo
    dependsOn:
      - dependencias
      - api-autenticacion

  # =========================================================================
  # MÓDULOS EN DESARROLLO
  # (Se comentan temporalmente para que el comando global no falle por falta de archivos)
  # =========================================================================
  step-function:
    path: stepFunction
      dependsOn:
       - dependencias

  # api-pedidos:
  #   path: pedidos
  #   dependsOn:
  #     - dependencias
  #     - step-function

  # api-operaciones:
  #   path: operaciones
  #   dependsOn:
  #     - dependencias

  # api-analitica:
  #   path: analitica
  #   dependsOn:
  #     - dependencias