service: burger-king-autenticacion

provider:
  name: aws
  runtime: python3.13
  region: us-east-1
  memorySize: 256
  timeout: 10
  iam:
    role: arn:aws:iam::${env:AWS_ACCOUNT_ID}:role/LabRole
  environment:
    TABLA_USUARIOS: ${env:TABLA_USUARIOS}
    TABLA_EMPLEADOS: ${env:TABLA_EMPLEADOS}
    TABLA_TOKENS: ${env:TABLA_TOKENS}
    JWT_SECRET: ${env:JWT_SECRET}
  httpApi:
    cors: true

# ¡Bloque global 'layers' eliminado para evitar el error de 'path'!

functions:
  crearUsuario:
    handler: handlers/crear_usuario.lambda_handler
    layers:
      - !ImportValue BurgerKing-Python-Layer-Version  # Importación directa
    events:
      - httpApi:
          method: POST
          path: /auth/register

  loginUsuario:
    handler: handlers/login_usuario.lambda_handler
    layers:
      - !ImportValue BurgerKing-Python-Layer-Version  # Importación directa
    events:
      - httpApi:
          method: POST
          path: /auth/login

  ValidarTokenAcceso:
    handler: handlers/validar_token.lambda_handler
    layers:
      - !ImportValue BurgerKing-Python-Layer-Version  # Importación directa

resources:
  Resources:
    UsuariosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:TABLA_USUARIOS}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: usuario_id
            AttributeType: S
        KeySchema:
          - AttributeName: usuario_id
            KeyType: HASH
            
    EmpleadosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:TABLA_EMPLEADOS}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: empleado_id
            AttributeType: S
        KeySchema:
          - AttributeName: empleado_id
            KeyType: HASH

    TokensTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:TABLA_TOKENS}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: token_id
            AttributeType: S
        KeySchema:
          - AttributeName: token_id
            KeyType: HASH